name: c3lr
channels:
  - conda-forge
  - pytorch-lts
  - fastai
  - nvidia
  - defaults
dependencies:
  - python=3.9.5
  - mamba
  - pytorch-lightning
  - kornia
  - matplotlib
  - scikit-learn
  - cudatoolkit=11.1
  - jupyter
  - ipywidgets
  - jupyter_contrib_nbextensions
  - jupyterlab
  - nbdev
  - wandb
  - fire
  - opencv
  - umap-learn
  - torchaudio
  - torchvision
  - pytorch
  - hdbscan
  - plotly
  - shortuuid
  - black
  - nodejs
  - ca-certificates
  - certifi
  - openssl
  - scikit-learn-intelex
  - seaborn
  - numpy
  - cython
  - colour
  - more-itertools
  - kaggle
  - torchmetrics
  - pip:
          - torchmeta
          - torchnet
          - higher
          - learn2learn
