_target_: unsupervised_meta_learning.protoclr.ProtoCLR

n_support: 1
n_query: 3
batch_size: 50
distance: euclidean
tau: 1.0
num_input_channels: 1
lr: 1e-3
inner_lr: 1e-3
lr_decay_step: 25000
lr_decay_rate: 5e-1
ae: True
gamma: 1e-3
clustering_algo: null
oracle_mode: False
use_entropy: False