# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Flatten": "01_nn_utils.ipynb",
         "conv_block": "03_cactus.ipynb",
         "ProtoNet": "03_cactus.ipynb"}

modules = ["nn_utils.py",
           "maml.py",
           "cactus.py"]

doc_url = "https://ojss.github.io/unsupervised_meta_learning/"

git_url = "https://github.com/ojss/unsupervised_meta_learning/tree/main/"

def custom_doc_links(name): return None
