# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Flatten": "01_nn_utils.ipynb",
         "conv3x3": "01_nn_utils.ipynb",
         "get_proto_accuracy": "01_nn_utils.ipynb",
         "OmniglotDataModule": "01b_data_loaders_pl.ipynb",
         "logger": "02b_maml_pl.ipynb",
         "ConvolutionalNeuralNetwork": "02b_maml_pl.ipynb",
         "get_accuracy": "02b_maml_pl.ipynb",
         "MAML": "02b_maml_pl.ipynb",
         "PrototypicalNetwork": "03_protonet_pl.ipynb",
         "ProtoModule": "03_protonet_pl.ipynb",
         "Partition": "04_cactus.ipynb",
         "CactusTaskLoader": "04_cactus.ipynb",
         "get_partition_kmeans": "04_cactus.ipynb",
         "DataOpt": "04_cactus.ipynb",
         "LoaderOpt": "04_cactus.ipynb",
         "load": "04_cactus.ipynb"}

modules = ["nn_utils.py",
           "pl_dataloaders.py",
           "maml.py",
           "protonets.py",
           "cactus.py"]

doc_url = "https://ojss.github.io/unsupervised_meta_learning/"

git_url = "https://github.com/ojss/unsupervised_meta_learning/tree/main/"

def custom_doc_links(name): return None
