# AUTOGENERATED! DO NOT EDIT! File to edit: 02_maml.ipynb (unless otherwise specified).

__all__ = []

# Cell
#export maml
from torchmeta.datasets.helpers import miniimagenet, omniglot
from torchmeta.utils.data import BatchMetaDataLoader
from torchmeta.utils.gradient_based import gradient_update_parameters
from torchmeta.modules import MetaModule, MetaSequential, MetaConv2d, MetaBatchNorm2d, MetaLinear

from learn2learn.vision.datasets import MiniImagenet as l2l_miniimgnet
import kornia as K
import higher

import numpy as np
import matplotlib.pyplot as plt
import torchvision
import torch
import torch.nn as nn
import torch.nn.functional as F
import tqdm

from collections import OrderedDict
from copy import deepcopy

