# AUTOGENERATED! DO NOT EDIT! File to edit: 01_nn_utils.ipynb (unless otherwise specified).

__all__ = ['Flatten']

# Cell
#export

import torchvision
import torch
import torch.nn as nn
import torch.nn.functional as F

# Cell

class Flatten(nn.Module):
    def __init__(self):
        super(Flatten, self).__init__()
    def forward(self, x):
        return x.view(x.shape[0], -1)